name: voi

services:
  voi-nextjs:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - DOMAIN=${DOMAIN}
        - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@voi-postgres:5432/postgres?schema=public
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - POSTMARK_API_KEY=${POSTMARK_API_KEY}
        - FROM_EMAIL=${FROM_EMAIL}
        - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
        - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
        - R2_BUCKET_NAME=${R2_BUCKET_NAME}
        - R2_ENDPOINT=${R2_ENDPOINT}
    expose:
      - 3000
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.voi.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.voi.entrypoints=web
      - traefik.http.services.voi.loadbalancer.server.port=3000
    depends_on:
      voi-postgres:
        condition: service_healthy
      voi-redis:
        condition: service_healthy
    restart: unless-stopped

  voi-postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - voi-postgres-data:/var/lib/postgresql/data
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  dokploy-network:
    external: true

volumes:
  voi-postgres-data:
